version: '2'

services:
  postgres:
    image: mdillon/postgis:9.6
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
      - GOOGLE_API_KEY=<YOUR_GOOGLE_API_KEY>
    image: web
    build: ./
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
  documentation:
    restart: always
    build: ./
    command: "mkdocs serve"
    volumes:
      - ./:/code
    ports:
      - "8001:8001"
