# Generated by Django 2.1.3 on 2018-11-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_auto_20181125_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='addition_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
